services:
  - type: web
    name: kanban-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: daphne -b 0.0.0.0 -p $PORT proyectofinal.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "kanban-backend.onrender.com,*.onrender.com"
      - key: USE_HTTPS
        value: "True"
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:5173,http://127.0.0.1:5173,https://heiner2001.github.io,https://heiner2001.github.io/ProyectoFinal"
      - key: CSRF_TRUSTED_ORIGINS
        value: "http://localhost:5173,http://127.0.0.1:5173,https://heiner2001.github.io,https://heiner2001.github.io/ProyectoFinal"
      - key: SESSION_COOKIE_SAMESITE
        value: "None"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SAMESITE
        value: "None"
      - key: CSRF_COOKIE_SECURE
        value: "True"

