services:
  # Backend Django
  - type: web
    name: proyectofinal-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py migrate
    startCommand: cd backend && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: proyectofinal-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: proyectofinal-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://proyectofinal-frontend.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://proyectofinal-frontend.onrender.com,https://proyectofinal-backend.onrender.com
      - key: USE_HTTPS
        value: True

  # Frontend React
  - type: web
    name: proyectofinal-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build:render
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://proyectofinal-backend.onrender.com

databases:
  - name: proyectofinal-db
    plan: free
    databaseName: proyectofinal
    user: proyectofinal_user
