services:
  - type: web
    name: kanban-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: daphne -b 0.0.0.0 -p $PORT proyectofinal.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "kanban-backend.onrender.com"
      - key: USE_HTTPS
        value: "True"
      - key: CORS_ALLOWED_ORIGINS
        sync: false  # Se configurará después de tener la URL del frontend
      - key: CSRF_TRUSTED_ORIGINS
        sync: false  # Se configurará después de tener la URL del frontend

